jobs:
    build:
      docker:
        - image: sillelien/circleci-dollar-build-image

      environment:
        MAJOR_VERSION: 0.1
        MAVEN_OPTS: "-Xmx1g -DbuildNumber=${CIRCLE_BUILD_NUM}  "
        TZ: "/usr/share/zoneinfo/Europe/London"

      working_directory: ~/build-utils-checkout

      branches:
        ignore:
          - gh-pages

      steps:

        - checkout

        - run:
            name: init
            command: . functions.sh


        - run:
            name: test
            command:  ./test.sh  && echo "PASSED"

        - deploy:
            command: |
              if [ "${CIRCLE_BRANCH}" == "staging" ]; then
                      ~/build-utils/promote_from_staging.sh
              fi
